# This file was generated by GoReleaser. DO NOT EDIT.
class 2f < Formula
  desc "Use build-in macOS security util to manage secrets in keychain storage."
  homepage "https://github.com/AlekseevAV/2f"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/AlekseevAV/2f/releases/download/v0.1.0/2f_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "4d4f99f67860ee3e69f521e1a2470e57448114ddb37ced52ea304e33508aa677"
  elsif OS.linux?
  end
  
  depends_on "go"

  def install
    bin.install "2f"
  end

  def caveats; <<~EOS
    Two-factor authentication agent
  EOS
  end

  test do
    system "#{bin}/2f -help"
  end
end
