# This file was generated by GoReleaser. DO NOT EDIT.
class F2f < Formula
  desc "Use build-in macOS security util to manage secrets in keychain storage."
  homepage "https://github.com/AlekseevAV/2f"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/AlekseevAV/2f/releases/download/v0.1.1/2f_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "878ad54ca0a020f904f4c62de45ee160f7d1ea8825c8afa30c6a694c4e1f84fb"
  elsif OS.linux?
  end
  
  depends_on "go"

  def install
    bin.install "2f"
  end

  def caveats; <<~EOS
    Two-factor authentication agent
  EOS
  end

  test do
    system "#{bin}/2f -help"
  end
end
