# This file was generated by GoReleaser. DO NOT EDIT.
class F2f < Formula
  desc "Use build-in macOS security util to manage secrets in keychain storage."
  homepage "https://github.com/AlekseevAV/2f"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/AlekseevAV/2f/releases/download/v0.2.0/2f_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "153e5466a1a656f009cf45949b25e3838f0cc2a0441d762cfbb171789914e4de"
  elsif OS.linux?
  end
  
  depends_on "go"

  def install
    bin.install "2f"
  end

  def caveats; <<~EOS
    Two-factor authentication agent
  EOS
  end

  test do
    system "#{bin}/2f -help"
  end
end
